### ISSUE TITLE
Workflows require .fastq.gz and should also look for .fq.gz

### ISSUE THREAD

**Issue by k-florek** [StaPH-B/staphb_toolkit#13]
We should update any workflows using paired data to use both .fastq.gz and .fq.gz extensions.

**Comment by kevinlibuit** [comment]
Introduced an

**Comment by kevinlibuit** [comment]
Made a quick fix with [6068a76](https://github.com/StaPH-B/staphb_toolkit/commit/6068a76c52209d7901b44768978a047fcd929a3c), but not super robust. Closing this issue and will open a separate and will address in the near future

**Comment by kevinlibuit** [comment]
Made a quick fix with [6068a76](https://github.com/StaPH-B/staphb_toolkit/commit/6068a76c52209d7901b44768978a047fcd929a3c), but not super robust. Closing this issue and will open a separate and will address in the near future
