### ISSUE TITLE
Update NCBI-AMRFINDER-Plus

### ISSUE THREAD

**Issue by k-florek** [StaPH-B/staphb_toolkit#18]
Update to 3.8 for enhanced point mutation detection

**Comment by kapsakcj** [comment]
Gotchu fam https://github.com/StaPH-B/docker-builds/blob/master/ncbi-amrfinderplus/3.8.4/Dockerfile

Tested and it works well in singularity, I assume is fine with docker as well.

**Comment by k-florek** [comment]
Thanks a bunch! I already used it today, the new version detected some point mutations the older version didn't!
