### ISSUE TITLE
Using custom .bed files

### ISSUE THREAD

**Issue by kevhill** [StaPH-B/staphb_toolkit#23]
Hello, I'm a COVID related volunteer for the Colorado Dept of Public Health. I have lots of experience with data pipelines, python, docker, etc, but am new to sequencing, nextflow, etc.

I've been asked to help use some custom .bed files to use some different primers in any of the ARTIC versions. I think this is possible, but would involve some minor changes to staphb. I think they would be generally useful, so I wanted to give an overview of my plans, ask for suggestions, and then see if you agree that this would be a valuable pr.

So, specifically the lab is using the monroe pipeline, which depends on ivar, which gets those .bed files from the `/reference` folder in the ivar docker image. I can't even find where in the ivar repo they generate that `/reference` folder, so I'm guessing it is pretty deep in one of their dependencies. Updating all of that seems like a headache.

However, since staphb is using nextflow to run the dockerized steps, I think I should be able to use [netflow's docker config options](https://www.nextflow.io/docs/latest/config.html#config-docker) to solve the issue. Specifically, to use the `runOptions` parameter to mount a new `/references` at runtime. So the new command would end up being something like:

```staphb-wf ... --runOptions "-v /path/to/custom/bed:/references" ... --primers custom_primer_name```

So, I think that should be pretty straight forward, and only involve changing the [toolkit_workflows.py](https://github.com/StaPH-B/staphb_toolkit/blob/f97e98c19f8a0d0450ff1c76120bc145b12fb383/staphb_toolkit/toolkit_workflows.py) file to add the relevant parsers and command builders.

I think this would be valuable for more than just the monroe pipeline, so I'd be happy to add it to all the subparsers if people agree this would be useful.

**Comment by kevhill** [comment]
Minor issues:
- I think I probably should name the staphb cli option `--containerRunOptions` to be clear
- It looks like the [existing parsers](https://github.com/StaPH-B/staphb_toolkit/blob/f97e98c19f8a0d0450ff1c76120bc145b12fb383/staphb_toolkit/toolkit_workflows.py#L50) for the `--primers` option has a set list of choices. I'd either need to remove that command arg, or add an extra value such as `'custom'`

**Comment by k-florek** [comment]
I agree that having this flexibility would be useful! One thing to keep in mind is we want to keep the functionality the same between docker and singularity as much as possible, especially at the CLI level. 

One approach to do this would be to set it up as a custom nextflow configuration option. When the custom configuration file is provided the `--primers` option could be setup to be overridden and the primers and runtime options would be provided in the config. This way the flexibility is there without adding additional cli options. If you want to open a PR with the changes to the user conifgs I can easily make the appropriate changes to the `--primers` option.

**Comment by kapsakcj** [comment]
Hey Kevin. I wanted to chime in about the `/reference` part of this. I believe the Monroe pipeline uses the `staphb/ivar:1.2.1_SC2` docker image which @kevinlibuit set up originally.

I think `/reference` directory your referring to is within this docker image? Maybe this will help explain? Here's the line in the dockerfile https://github.com/StaPH-B/docker-builds/blob/0aca55098809922020196ddaa048440edd0b4d9f/ivar/1.2.2_artic20200528/Dockerfile#L37

This is a separate docker image that is based on the andersenlab ivar docker image, but with some additional things added in by Kevin Libuit.

@erinyoung has also created a docker image with a newer version of ivar (1.2.2) along with V1-V3 ARTIC primer bedfiles. https://github.com/StaPH-B/docker-builds/blob/master/ivar/1.2.2_artic20200528/Dockerfile

We could tweak one of the docker images if you don't want to have to input custom nextflow options every time you run the pipeline. I'm happy to help set up another docker image under a different docker image tag if that would make things easier.

Curtis

**Comment by erinyoung** [comment]
I don't think it'd be a great use of time to create a docker image every time someone has a custom primer set. Like @k-florek mentioned, it's fairly easy to add in a primer bed parameter, with the default being the artic V3 bedfile.

**Comment by kevhill** [comment]
Thanks for the quick replies!

@k-florek it looks like singularity also has the same config `runOptions` so, this would definitely work for both setups. Though a custom nextflow config option is interesting too... one kind of hacky thing is that right now the [nextflow file hard-codes part of the .bed file](https://github.com/StaPH-B/staphb_toolkit/blob/f7e091a8686e2cbfef9951bafb98dadc284a389f/staphb_toolkit/workflows/monroe/monroe_pe_assembly.nf#L103) as `/reference/ARTIC-${params.primers}.bed` so even if we had a custom primers var, they'd need to name the files something like `ARTIC-foo.bed` even when the custom primers aren't part of ARTIC technically. Those type of little gotchas can be hard to explain, but I also don't want to be too disruptive of the existing pipeline. I'm thinking your idea of extending the custom nextflow config would make that change a bit more manageable. Let me look more closely at that and I'll get back to you.

@kapsakcj I think @erinyoung is right here. I've heard they want to try "3 or 4" new primer sets. And that's from just one lab...

**Comment by kapsakcj** [comment]
Ah ok, make sense! I didn't realize that there were more primer sets being used.

**Comment by kevhill** [comment]
@k-florek thanks for pointing me in the direction of the custom configs. I think I could do everything through that. I think basically I just need to build them a config like:

```
includeConfig "nextflow.config"

profiles {
  docker {
    docker.runOptions = "-v /blah/blah:/references"
  }
}
```

Then with no code changes to staphb we could make it work, as long as they named the files as `['ARTIC-V1.bed', 'ARTIC-V2.bed', 'ARTIC-V3.bed']`. Though that would be a bit hacky and confusing... 

So to address that confusion, now I'd like your thoughts on a different set of proposed changes:
- remove the `choice` [from the subparser](https://github.com/StaPH-B/staphb_toolkit/blob/f7e091a8686e2cbfef9951bafb98dadc284a389f/staphb_toolkit/toolkit_workflows.py#L50)
- add a new value `params.primer_prefix = "ARTIC-"` to [monroe.config](https://github.com/StaPH-B/staphb_toolkit/blob/f97e98c19f8a0d0450ff1c76120bc145b12fb383/staphb_toolkit/workflows/monroe/monroe.config)
- change the [monroe_pre_assembly.nf](https://github.com/StaPH-B/staphb_toolkit/blob/f97e98c19f8a0d0450ff1c76120bc145b12fb383/staphb_toolkit/workflows/monroe/monroe_pe_assembly.nf#L103) ivar line to use both `params.primer_prefix` and `params.primers` to find the .bed file

With that, then anyone could overwrite `params.primer_prefix` and mount volumes in their custom config, and put any specific primer file at runtime. Current users wouldn't notice any change at all, so no doc changes!

I'd be happy to do that for all of the different pipelines that use primers, just for consistency.

**Comment by kevhill** [comment]
Hello @k-florek did you get a chance to look at the PR I put up on this? I know we all lead busy lives, so no worry if you haven't gotten to it yet.

**Comment by k-florek** [comment]
@kevhill sorry for the delay. I made a couple of edits so that you can customize the path of the primer selection in the docker container. Let me know if this edit works on your end!
