### ISSUE TITLE
execution of certain containers do not complete with python v3.7.9 and python v3.8

### ISSUE THREAD

**Issue by SESchmedes** [StaPH-B/staphb_toolkit#28]
I use staphb-tk tools in my various pipelines. When running a basic read trimming/filtering, assembly, and annotation pipeline, my runs will execute but never finish and just time out when using python v3.7.9 and python v3.8.6 (using anaconda3). It starts staphb-tk prokka and then gets hung up and never finishes. Works just fine with python v3.7.4 (when that is the default python version with anaconda. Does not work with v3.7.4 when in a separate env when v3.8 is the default anaconda version). (This was tested on same dataset on an HPC - using singularity).

**Comment by moskalenko** [comment]
Here's a bit more detail

* Running prokka via 'staphb-tk prokka ...'  hangs while executing the following stage:
perl /prokka-1.14.5/bin/prokka --cpus 8 --genus Escherichia --species coli --strain 2020LY00001 --outdir 2020-10-18_flaq_run/2020LY00001/2020LY00001_assembly/prokka --prefix 2020LY00001 --force --compliant -

last log message:

"write(2, "[12:35:13] Fixed 2 duplicate /ge"..., 51"

which appears to be right around this area

[10:08:20] Fixed 2 duplicate /gene - silE_1 silE_2 <-- hangs here or in one of other duplicate fixes.
[10:08:20] Fixed 263 colliding /gene names.
[10:08:20] Adding /locus_tag identifiers
[10:08:20] Assigned 4922 locus_tags to CDS and RNA features.

* Running prokka manually from the prokka container image downloaded by staphb run works fine and completes successfully
singularity exec --bind /data/apps/tests/staphb-toolkit/20201015_GA_flaq_amr_test:/data --pwd /data --cleanenv docker://staphb/prokka:1.14.5 prokka --cpus 8 --genus Escherichia --species coli --strain  2020LY00001 --outdir 2020-10-18_flaq_run/2020LY00001/2020LY00001_assembly/prokka_staphb --prefix 2020LY00001 --force --compliant --locustag Escherichia 2020-10-18_flaq_run/2020LY00001/2020LY00001_assembly/2020LY00001.fasta

which is the same command that's generated by 

staphb-tk prokka --cpus 8 --genus Escherichia --species coli --strain 2020LY00001 --outdir 2020-10-18_flaq_run/2020LY00001/2020LY00001_assembly/prokka --prefix 2020LY00001 --force --compliant --locustag Escherichia 2020-10-18_flaq_run/2020LY00001/2020LY00001_assembly/2020LY00001.fasta

**Comment by SESchmedes** [comment]
Another update. This is not related to python versions as I originally thought. I changed the staphb-tk prokka command in our pipeline to a singularity exec command using a locally stored container and it worked just fine for one user, but then the pipeline got hung up again for another user at the staphb-tk mlst step. It appears the issue may be related to staphb-tk pulling the containers (perhaps related to recent changes made at dockerhub, not sure). In the meantime, we will switch to using our local containers.

**Comment by k-florek** [comment]
@SESchmedes 
@moskalenko 

I just released version 1.2.2 of the toolkit which now allows you to specify a local singularity image or even images from other container registries. I did some testing and I wasn't able to recreate the issue described here but hopefully the added functionality of being able to use local singularity images will help resolve this.

To use the local images use the `staphb-tk --get_docker_config` and change the image parameter in the docker_config.json file. Then run the toolkit using the -c parameter. Note if you are using a local singularity image the "tag" will be ignored.

I'm closing this issue but feel free to re-open if you encounter the same or another issue related to this.
