### ISSUE TITLE
Cutshaw Spades Memory

### ISSUE THREAD

**Issue by logan-fink** [StaPH-B/staphb_toolkit#41]
In the Cutshaw workflow, cutshaw.nf keeps hitting a snag when I run it on my machine, and it has to do with the ${task.memory} variable, it returns "4 GB", and SPAdes can't seem to handle the "GB" part.  It thinks there's a new variable that we haven't assigned:

Error executing process > 'spades (sample1)'

Caused by:
  Process `spades (sample1)` terminated with an error exit status (1)

Command executed:

  spades.py --memory 4 GB -1 sample1_S12_L001_R1_001.fastq.gz -2 sample1_S12_L001_R2_001.fastq.gz -o ./spades_out
  mv ./spades_out/contigs.fasta sample1_S12_L001_contigs.fasta

Command exit status:
  1

Command output:

  == Error ==  Please specify option (e.g. -1, -2, -s, etc) for the following paths: GB

I just hard coded it to "4" in the nextflow script in the toolkit on my computer, but there's probably a better fix somewhere, I just didn't have time to figure it out.  Let me know if this is confusing, and I'll clarify!  Thanks!

**Comment by k-florek** [comment]
Thanks for finding this, I updated the parameters but I missed this one for spades. There is an easy fix for this by adding the toGiga() function which will convert the string into a usable memory parameter. Thanks for finding this. If you want to update the fix your self simply add `${task.memory.toGiga()}`. I plan to do a release later today and I will incorporate the fix then!
