### ISSUE TITLE
ivar not trimming primers in Monroe pipeline

### ISSUE THREAD

**Issue by jgarbe256** [StaPH-B/staphb_toolkit#42]
I recently installed the staphb toolkit to run the monroe pipeline  (staphb-wf monroe pe_assembly fastq -o output --primer V3). Looking at one of the .command.out files in the logs/work folder I see the stdout from ivar, and it prints a note about the required columns in the (primer) BED file, and reports that it trimmed primers from 0 reads. Normally ivar would report how many primers were found in the BED file. It appears that the primer bed file provided to ivar in the Monroe pipeline isn't formatted correctly or isn't being found. I haven't been able to figure out where the primer BED file ivar is using is coming from (/reference/ARTIC-V3.bed)

```
1016027 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
1500 + 0 supplementary
0 + 0 duplicates
1016027 + 0 mapped (100.00% : N/A)
1014527 + 0 paired in sequencing
507258 + 0 read1
507269 + 0 read2
1014150 + 0 properly paired (99.96% : N/A)
1014506 + 0 with itself and mate mapped
21 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
iVar uses the standard 6 column BED format as defined here - https://genome.ucsc.edu/FAQ/FAQformat.html#format1.
It requires the following columns delimited by a tab: chrom, chromStart, chromEnd, name, score, strand

Number of references in file: 1
MN908947.3
Using Region: MN908947.3

Found 1016027 mapped reads
Found 0 unmapped reads
Sorted By Coordinate
-------
Processed 10% reads ...
Processed 20% reads ...
Processed 30% reads ...
Processed 40% reads ...
Processed 50% reads ...
Processed 60% reads ...
Processed 70% reads ...
Processed 80% reads ...
Processed 90% reads ...
Processed 100% reads ...

-------
Results:
Primer Name	Read Count

Trimmed primers from 0% (0) of reads.
0.02% (165) of reads were quality trimmed below the minimum length of 30 bp and were not writen to file.
99.98% (1015862) of reads started outside of primer regions. Since the -e flag was given, these reads were written to file.
```

**Comment by kevinlibuit** [comment]
@jgarbe256 wow, great catch. I'll have some time this weekend to look deeper into this. In the meantime, if you're working with Illumina PE data, I suggest analyzing with the Cecret workflow--also available in the StaPH-B ToolKit
