### ISSUE TITLE
Possible report generation hang

### ISSUE THREAD

**Issue by codybum** [StaPH-B/staphb_toolkit#44]
I am trying to generate a report for 18 sequences that were already processed by the pe_assembly step.  Things seem to process without error and there is a great deal of resource utilization until the render step.  At at the document generation step (pandoc) of render the process appears to hang.  There is no cpu usage and there is no data being written to the output folder, or as far as I can tell (docker shell on running container) the directories within the Docker container.

Does this seem normal, should this process take a long time?   

Code version:
master (today, 4/6/2021)

Run command:
./staphb-wf monroe cluster_analysis test -o results 

Output:
Starting the Monroe cluster analysis:
N E X T F L O W  ~  version 20.10.0
Launching `/home/cody/staphb_toolkit/staphb_toolkit/workflows/monroe/monroe_cluster_analysis.nf` [berserk_hamilton] - revision: cc45af1307
executor >  local (4)
[45/a770f6] process > msa        [100%] 1 of 1 ✔
[cc/316b0f] process > snp_matrix [100%] 1 of 1 ✔
[e1/c32ea7] process > iqtree     [100%] 1 of 1 ✔
[5c/2eddec] process > render (1) [  0%] 0 of 1

Docker container: staphb/cluster-report-env:1.0
Docker container log tail:

output file: report_template.knit.md

/usr/bin/pandoc +RTS -K512m -RTS report_template.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output report.tex --self-contained --highlight-style tango --latex-engine xelatex --variable graphics --include-in-header /tmp/Rtmp7TIwqp/rmarkdown-str1e12d54db9.html --variable 'geometry:margin=1in' 

contents of Docker working directory:
drwxrwxr-x 3 1000 1000   4096 Apr  6 21:39 .
drwxrwxr-x 3 1000 1000   4096 Apr  6 21:39 ..
-rw-rw-r-- 1 1000 1000      0 Apr  6 21:39 .command.begin
-rw-rw-r-- 1 1000 1000    410 Apr  6 21:39 .command.err
-rw-rw-r-- 1 1000 1000   4361 Apr  6 21:39 .command.log
-rw-rw-r-- 1 1000 1000   3951 Apr  6 21:39 .command.out
-rw-rw-r-- 1 1000 1000   9873 Apr  6 21:39 .command.run
-rw-rw-r-- 1 1000 1000    357 Apr  6 21:39 .command.sh
-rw-r--r-- 1 root root      0 Apr  6 21:39 .command.trace
lrwxrwxrwx 1 1000 1000     93 Apr  6 21:39 040621_msa.tree -> /home/cody/staphb_toolkit/results/logs/work/e1/c32ea70e9ba082ebd6222617717087/040621_msa.tree
-rw-r--r-- 1 root root  35153 Apr  6 21:39 ML_tree.png
-rw-r--r-- 1 root root 254832 Apr  6 21:39 SNP_heatmap.png
lrwxrwxrwx 1 1000 1000    110 Apr  6 21:39 pairwise_snp_distance_matrix.tsv -> /home/cody/staphb_toolkit/results/logs/work/cc/316b0f487721e338e15b2b3cbc7bdd/pairwise_snp_distance_matrix.tsv
lrwxrwxrwx 1 1000 1000     75 Apr  6 21:39 report.Rmd -> /home/cody/staphb_toolkit/staphb_toolkit/workflows/monroe/report/report.Rmd
-rw-r--r-- 1 root root   6952 Apr  6 21:39 report.log
-rw-r--r-- 1 root root   4988 Apr  6 21:39 report.tex
drwxr-xr-x 3 root root   4096 Apr  6 21:39 report_files
-rw-r--r-- 1 root root   8022 Apr  6 21:39 report_template.Rmd
-rw-r--r-- 1 root root   3053 Apr  6 21:39 report_template.knit.md
-rw-r--r-- 1 root root   3053 Apr  6 21:39 report_template.utf8.md
-rw-r--r-- 1 root root   1165 Apr  6 21:39 snp_distance_matrix.tsv

**Comment by kevinlibuit** [comment]
@codybum thanks for posting this. I think it may have to do with the local tex live version being out of sync with the remote repo. This is a frustrating behavior in these R packages that @AbigailShockey and I ran into and spoke about last week with a similar report generator. Can you check or post the contents of that report log? If there's something in there along the lines of "tlmgr: Local TeX Live (2020) is older than remote repository (2021)." this is the cause.

@AbigailShockey if this is it, we may have to update the dockerfile for cluster-report-env

**Comment by codybum** [comment]
Ah, report.log would have been a reasonable place to look for the report logs.  This looks to be the issue:

! LaTeX Error: File `mathspec.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.


Full: report.log

This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex 2020.7.8)  6 APR 2021 21:56
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**report.tex
(./report.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-06-18> (/root/.TinyTeX/texmf-dist/tex/latex/base/art
icle.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/root/.TinyTeX/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2019/12/20 v1.4l Standard LaTeX file (size option)
)
\c@part=\count163
\c@section=\count164
\c@subsection=\count165
\c@subsubsection=\count166
\c@paragraph=\count167
\c@subparagraph=\count168
\c@figure=\count169
\c@table=\count170
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen134
) (/root/.TinyTeX/texmf-dist/tex/latex/lm/lmodern.sty
Package: lmodern 2009/10/30 v1.6 Latin Modern Fonts
LaTeX Font Info:    Overwriting symbol font `operators' in version `normal'
(Font)                  OT1/cmr/m/n --> OT1/lmr/m/n on input line 22.
LaTeX Font Info:    Overwriting symbol font `letters' in version `normal'
(Font)                  OML/cmm/m/it --> OML/lmm/m/it on input line 23.
LaTeX Font Info:    Overwriting symbol font `symbols' in version `normal'
(Font)                  OMS/cmsy/m/n --> OMS/lmsy/m/n on input line 24.
LaTeX Font Info:    Overwriting symbol font `largesymbols' in version `normal'
(Font)                  OMX/cmex/m/n --> OMX/lmex/m/n on input line 25.
LaTeX Font Info:    Overwriting symbol font `operators' in version `bold'
(Font)                  OT1/cmr/bx/n --> OT1/lmr/bx/n on input line 26.
LaTeX Font Info:    Overwriting symbol font `letters' in version `bold'
(Font)                  OML/cmm/b/it --> OML/lmm/b/it on input line 27.
LaTeX Font Info:    Overwriting symbol font `symbols' in version `bold'
(Font)                  OMS/cmsy/b/n --> OMS/lmsy/b/n on input line 28.
LaTeX Font Info:    Overwriting symbol font `largesymbols' in version `bold'
(Font)                  OMX/cmex/m/n --> OMX/lmex/m/n on input line 29.
LaTeX Font Info:    Overwriting math alphabet `\mathbf' in version `normal'
(Font)                  OT1/cmr/bx/n --> OT1/lmr/bx/n on input line 31.
LaTeX Font Info:    Overwriting math alphabet `\mathsf' in version `normal'
(Font)                  OT1/cmss/m/n --> OT1/lmss/m/n on input line 32.
LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `normal'
(Font)                  OT1/cmr/m/it --> OT1/lmr/m/it on input line 33.
LaTeX Font Info:    Overwriting math alphabet `\mathtt' in version `normal'
(Font)                  OT1/cmtt/m/n --> OT1/lmtt/m/n on input line 34.
LaTeX Font Info:    Overwriting math alphabet `\mathbf' in version `bold'
(Font)                  OT1/cmr/bx/n --> OT1/lmr/bx/n on input line 35.
LaTeX Font Info:    Overwriting math alphabet `\mathsf' in version `bold'
(Font)                  OT1/cmss/bx/n --> OT1/lmss/bx/n on input line 36.
LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `bold'
(Font)                  OT1/cmr/bx/it --> OT1/lmr/bx/it on input line 37.
LaTeX Font Info:    Overwriting math alphabet `\mathtt' in version `bold'
(Font)                  OT1/cmtt/m/n --> OT1/lmtt/m/n on input line 38.
) (/root/.TinyTeX/texmf-dist/tex/latex/amsfonts/amssymb.sty
Package: amssymb 2013/01/14 v3.01 AMS font symbols
(/root/.TinyTeX/texmf-dist/tex/latex/amsfonts/amsfonts.sty
Package: amsfonts 2013/01/14 v3.01 Basic AMSFonts support
\@emptytoks=\toks15
\symAMSa=\mathgroup4
\symAMSb=\mathgroup5
LaTeX Font Info:    Redeclaring math symbol \hbar on input line 98.
LaTeX Font Info:    Overwriting math alphabet `\mathfrak' in version `bold'
(Font)                  U/euf/m/n --> U/euf/b/n on input line 106.
)) (/root/.TinyTeX/texmf-dist/tex/latex/amsmath/amsmath.sty
Package: amsmath 2020/01/20 v2.17e AMS math features
\@mathmargin=\skip49
For additional information on amsmath, use the `?' option.
(/root/.TinyTeX/texmf-dist/tex/latex/amsmath/amstext.sty
Package: amstext 2000/06/29 v2.01 AMS text
(/root/.TinyTeX/texmf-dist/tex/latex/amsmath/amsgen.sty
File: amsgen.sty 1999/11/30 v2.0 generic functions
\@emptytoks=\toks16
\ex@=\dimen135
)) (/root/.TinyTeX/texmf-dist/tex/latex/amsmath/amsbsy.sty
Package: amsbsy 1999/11/29 v1.2d Bold Symbols
\pmbraise@=\dimen136
) (/root/.TinyTeX/texmf-dist/tex/latex/amsmath/amsopn.sty
Package: amsopn 2016/03/08 v2.02 operator names
)
\inf@bad=\count171
LaTeX Info: Redefining \frac on input line 227.
\uproot@=\count172
\leftroot@=\count173
LaTeX Info: Redefining \overline on input line 389.
\classnum@=\count174
\DOTSCASE@=\count175
LaTeX Info: Redefining \ldots on input line 486.
LaTeX Info: Redefining \dots on input line 489.
LaTeX Info: Redefining \cdots on input line 610.
\Mathstrutbox@=\box45
\strutbox@=\box46
\big@size=\dimen137
LaTeX Font Info:    Redeclaring font encoding OML on input line 733.
LaTeX Font Info:    Redeclaring font encoding OMS on input line 734.
\macc@depth=\count176
\c@MaxMatrixCols=\count177
\dotsspace@=\muskip16
\c@parentequation=\count178
\dspbrk@lvl=\count179
\tag@help=\toks17
\row@=\count180
\column@=\count181
\maxfields@=\count182
\andhelp@=\toks18
\eqnshift@=\dimen138
\alignsep@=\dimen139
\tagshift@=\dimen140
\tagwidth@=\dimen141
\totwidth@=\dimen142
\lineht@=\dimen143
\@envbody=\toks19
\multlinegap=\skip50
\multlinetaggap=\skip51
\mathdisplay@stack=\toks20
LaTeX Info: Redefining \[ on input line 2859.
LaTeX Info: Redefining \] on input line 2860.
) (/root/.TinyTeX/texmf-dist/tex/generic/iftex/ifxetex.sty
Package: ifxetex 2019/10/25 v0.7 ifxetex legacy package. Use iftex instead.
(/root/.TinyTeX/texmf-dist/tex/generic/iftex/iftex.sty
Package: iftex 2020/03/06 v1.0d TeX engine tests
)) (/root/.TinyTeX/texmf-dist/tex/generic/iftex/ifluatex.sty
Package: ifluatex 2019/10/25 v1.5 ifluatex legacy package. Use iftex instead.
) (/root/.TinyTeX/texmf-dist/tex/latex/base/fixltx2e.sty
Package: fixltx2e 2016/12/29 v2.1a fixes to LaTeX (obsolete)
Applying: [2015/01/01] Old fixltx2e package on input line 46.

Package fixltx2e Warning: fixltx2e is not required with releases after 2015
(fixltx2e)                All fixes are now in the LaTeX kernel.
(fixltx2e)                See the latexrelease package for details.

Already applied: [0000/00/00] Old fixltx2e package on input line 53.
)

! LaTeX Error: File `mathspec.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.12   \else
            ^^M 
Here is how much of TeX's memory you used:
 1418 strings out of 481269
 15916 string characters out of 5925378
 250712 words of memory out of 5000000
 18998 multiletter control sequences out of 15000+600000
 532346 words of font info for 25 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 30i,0n,31p,231b,40s stack positions out of 5000i,500n,10000p,200000b,80000s

No pages of output.

**Comment by codybum** [comment]
I rebuilt the staphb/cluster-report-env:1.0 container from the Dockerfile and that seems to have done the trick.  My guess is you were right about the R packages.

**Comment by codybum** [comment]
I rebuilt the staphb/cluster-report-env:1.0 container from the Dockerfile and that seems to have done the trick. My guess is you were right about the R packages.

**Comment by kevinlibuit** [comment]
@codybum that's great news! 

So we should be able to rebuild the public docker image within the dockerhub without modifying the dockerfile so that folks are pulling an image with an updated R package. Not sure how this stands with best practices RE DockerHub image maintenance. Tagging @kapsakcj as he controls the StaPH-B DockerHub and may have better insight

**Comment by kapsakcj** [comment]
I can re-build the docker image named `staphb/cluster-report-env:1.0` on dockerhub. Is that what you all need? 

What about the next version `staphb/cluster-report-env:1.1` ?

Rebuilding the image will impact anyone using that docker image, but I think it's OK since this image is has small user base - only folks using the staphb_toolkit + monroe workflow will be impacted, correct?

**Comment by codybum** [comment]
The best approach is not clear.  As mentioned, there are differences between modules and time that fall into a difficult space with docker versioning.  One approach would be to increment Docker versions over time when CI test fail.  Updating the same version of the container with different content would likely not be the best way to go.  Either way it is an unfortunate issue.

**Comment by kapsakcj** [comment]
> Updating the same version of the container with different content would likely not be the best way to go. Either way it is an unfortunate issue.

Agreed - I'd rather not update the container without letting users know that things are changing (by releasing a new DockerHub tag), but in this case we have a non-functional container. So for that reason I'm OK with rebuilding the container under the same tag.

But since this container & corresponding dockerfile(s) is maintained by @AbigailShockey I will let them decide if we should rebuild the container under the same tag `:1.0` or create a new tag

I'm happy to add a new docker image tag on dockerhub, e.g. `staphb/cluster-report-env:1.2` but that means that we need a new dockerfile in our docker-builds repo: `/cluster-report-env/1.2/Dockerfile` Additionally that might also mean that the staphb_toolkit would need updating to use the new docker image tag?

Let me know what you'd like to do - I'm happy to help.

**Comment by AbigailShockey** [comment]
@kapsakcj I'm for rebuilding the container over creating a new tag. I'm going to look into why this container isn't static/needed to be rebuilt (clearly something is going on on the LAteX side of things).

**Comment by kapsakcj** [comment]
Thanks for your input @AbigailShockey I'll go ahead and rebuild the docker image: `staphb/cluster-report-env:1.0` on dockerhub.

Let me know if you all need anything else 👍

**Comment by kittychaseNC** [comment]
Hey @kapsakcj let me know when you rebuild the image.  I've been unsuccessful in finding a workaround and hesitant to try the rebuild on my own.

**Comment by kapsakcj** [comment]
Hi @kittychaseNC it has been re-built!
