### ISSUE TITLE
Allow demultipled reads in dirs not named "barcode*" for the monroe ont_assembly workflow

### ISSUE THREAD

**Issue by garfinjm** [StaPH-B/staphb_toolkit#50]
Currently the `monroe ont_assembly` workflow only works with demultiplexed reads that are stored in folders named `barcode*`.  For our lab at least, it would be helpful if the subdirectories of `params.fastq_dir` were allowed to have any name, so we can have our normal sample ID attached to the intermedaite and output files rather than the name of the barcode we put on the sequencer.

This change could cause issues if labs don't have their demultiplexed read dirs isolated in their own directory, but I don't see that being the case for most labs.

I'll do a PR with a potential solution later tonight or tomrrow.

**Comment by k-florek** [comment]
Sounds like a good idea! Since the fastq's from Guppy basecalling are put into sub directories I think it makes sense to mimic that on the input.
