### ISSUE TITLE
Error when trying to run monroe workflow

### ISSUE THREAD

**Issue by SESchmedes** [StaPH-B/staphb_toolkit#66]
I get the following error when trying to run the monroe clearlabs workflow. I am running on an HPC with a SLURM scheduler (submitting job via SBATCH script). 

Command in sbatch script:
`staphb-wf monroe clearlabs_assembly fastqs/ --profile singularity -c 21-07-12_clearlabs_assembly.config`

I edited the config file to use local containers. However, I get this same error when just using the default config file with singularity.
```
Traceback (most recent call last):
  File "/home/schmedess/anaconda3/bin/staphb-wf", line 10, in <module>
    sys.exit(main())
  File "/home/schmedess/anaconda3/lib/python3.7/site-packages/staphb_toolkit/toolkit_workflows.py", line 336, in main
    child.interact()
  File "/home/schmedess/anaconda3/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 788, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
```

**Comment by kevinlibuit** [comment]
Are you able to run any other toolkit workflow on that HPC with the same SLURM scheduler and a similar sbatch script?

**Comment by SESchmedes** [comment]
Yes. I am able to run the Tredegar workflow on this HPC using both default containers and local containers specified in the config file.

**Comment by k-florek** [comment]
Workflows have been migrated out of the toolkit and will have their own repositories going forward.
