### ISSUE TITLE
Changing to ArticV4 Primer Scheme

### ISSUE THREAD

**Issue by ABissonn** [StaPH-B/staphb_toolkit#74]
Hello Kelsey and Erin,
     Our SARS-CoV-2 NGS group recently transitioned to the ArticV4 Primers.  I have created text files from the ARTIC group's github page, I was wondering how I go about implementing the bed files, both the primer and insert, into the Cecret workflow.  The files are just text files created by copying and pasting the contents from the ARTIC group's nCoV-2019 primer scheme pagee into new notepad documents, and saving as a text file.  Do i just save the files on our server in the >root directory and change our cecret config file?  I found the location of the current primer and insert bed files (/root/anaconda3/lib/python3.8/site-packages/staphb_toolkit/workflows/cecret/configs/artic_V3_nCoV-2019.bed and /root/anaconda3/lib/python3.8/site-packages/staphb_toolkit/workflows/cecret/configs/nCoV-2019.insert.bed) on our Linux server I have access to through the Marshfield Clinic, but being less than a computer science novice, I do not want to disturb anything that would affect the many other labs using the same workflow, so will hold off on making any changes that would potentially affect the workflow everyone else is using.  Thanks.

Adam Bissonnette

bissonnette.adam@marshfieldresearch.org or abissonn@gmail.com

**Comment by k-florek** [comment]
Hi Adam,

The configuration file is where you can update which primer and insert bed files to use. Look for the section in the configuration file that looks like this:
```
//# Reference files for SARS-CoV-2 (part of the github repository)
//params.reference_genome = "Cecret/configs/MN908947.3.fasta"
//params.gff_file = "Cecret/configs/MN908947.3.gff"
//params.primer_bed = "Cecret/configs/artic_V3_nCoV-2019.bed"
//params.amplicon_bed = "Cecret/configs/nCoV-2019.insert.bed"
```
Just remember to remove the comments `//` for the lines you are changing and point to the new files you want to use.

**Comment by erinyoung** [comment]
@ABissonn,

I think the easiest option for you is to create a config file for your use case. In your config file, change the 'params.primer_bed' parameter to the location of your primer bedfile.

You'll also want to update 'params.amplicon_bed' to the new location of a bedfile of your amplicons or set 'params.bedtools_multicov = false'

More information can be found at: 

https://github.com/StaPH-B/staphb_toolkit/tree/main/staphb_toolkit/workflows/cecret

To get a copy of an editable config file, use 

'''
staphb-wf cecret --get_config
'''

**Comment by ABissonn** [comment]
Erin and Kelsey,
     Just to confirm though, I would place my new files in that same cecret workflow folder as the current v3 primer and insert beds I am accessing through our linux server?  And text files are ok or should I just not save them with a .txt suffix?  I have attached the files I created in this message.  

My new config file settings for reference files:
//# Reference files for SARS-CoV-2 (part of the github repository)
//params.reference_genome = "Cecret/configs/MN908947.3.fasta"
//params.gff_file = "Cecret/configs/MN908947.3.gff"
params.primer_bed = "Cecret/configs/nCoV-2019_ArticV4_Primer_bedfile.txt"
params.amplicon_bed = "Cecret/configs/nCoV-2019_ArticV4_Insert_bedfile.txt"
     
Adam

[nCoV-2019_ArticV4_Insert_bedfile.txt](https://github.com/StaPH-B/staphb_toolkit/files/7232188/nCoV-2019_ArticV4_Insert_bedfile.txt)

[nCoV-2019_ArticV4_Primer_bedfile.txt](https://github.com/StaPH-B/staphb_toolkit/files/7232189/nCoV-2019_ArticV4_Primer_bedfile.txt)

**Comment by erinyoung** [comment]
You could do that if you wanted, or you could put it elsewhere. You just need to specify the location of the file. 

params.primer_bed = "Cecret/configs/nCoV-2019_ArticV4_Primer_bedfile.txt" works if you move your files into Cecret/configs start the workflow in the same directory as Cecret.nf. 

This is a relative path, so I don't really recommend it. 

I recommend putting the full path of the file, just in case you want to move your config file around or your fastq files.

Something like 
```
params.primer_bed = "/home/Adam/artic-ncov2019/primer_schemes/nCoV-2019/V4/SARS-CoV-2.primer.bed"
```
Or wherever your files are.
