### ISSUE TITLE
Erroe while runing the Cecret workflow

### ISSUE THREAD

**Issue by elijou** [StaPH-B/staphb_toolkit#77]
I am trying to run Cecret wokflow using the command 
staphb-wf cecret /paired-end-reads --output /result --profile docker 
I am having the following issue

Error executing process > 'fastqc (1)'

Caused by:
  Process `fastqc (1)` terminated with an error exit status (1)

Command executed:

  mkdir -p fastqc logs/fastqc
  log_file=logs/fastqc/1.14d0e3e2-9b7d-49e8-9061-485eef68cef0.log
  err_file=logs/fastqc/1.14d0e3e2-9b7d-49e8-9061-485eef68cef0.err
  
  # time stamp + capturing tool versions
  date | tee -a $log_file $err_file > /dev/null
  fastqc --version >> $log_file
  
  fastqc        --outdir fastqc       --threads 1       1_S1_L001_R1.fastq.gz 1_S1_L001_R2.fastq.gz       2>> $err_file >> $log_file
  
  zipped_fastq=($(ls fastqc/*fastqc.zip) "")
  
  raw_1=$(unzip -p ${zipped_fastq[0]} */fastqc_data.txt | grep "Total Sequences" | awk '{ print $3 }' )
  raw_2=NA
  if [ -f "${zipped_fastq[1]}" ] ; then raw_2=$(unzip -p fastqc/*fastqc.zip */fastqc_data.txt | grep "Total Sequences" | awk '{ print $3 }' ) ; fi
  
  if [ -z "$raw_1" ] ; then raw_1="0" ; fi
  if [ -z "$raw_2" ] ; then raw_2="0" ; fi

Command exit status:
  1

Command output:
  (empty)

Command error:
  touch: cannot touch '.command.trace': Permission denied

Can you please guide me to fix this issue?

**Comment by erinyoung** [comment]
Thank you for including the whole error message! This is very helpful.

It looks like you're trying to create your working files in a directory that you don't have permissions for. 

It might be helpful to set the `workflow.workDir` in a config file to someplace you can write to. You can test if you can write to a directory by attempting
```
touch test.empty
```
or
```
touch <full path to where you want your working directory>/test.empty
```

Normally, the working directory (and directory where the results get published) is created in the place where you launched your command. If you can't write a working directory where you're launching the workflow, it's also likely that your `params.outdir` will need to be adjusted as well.

**Comment by elijou** [comment]
I have tried the commands you have mentioned but getting the same error

**Comment by erinyoung** [comment]
So even 
```
touch test.empty
```
is giving you a permissions error?

Is there a directory in your setup where you have write permissions for?

**Comment by elijou** [comment]
touch test.empty
writes the file in the working directory but having the same permission error while running the workflow

**Comment by erinyoung** [comment]
Looking at your original command, you're trying to write files to 
`/result`

Does
```
touch /result/test.empty
```
give you permission errors?

**Comment by erinyoung** [comment]
Were you able to resolve your issue?
